{
	"version": 1585585888,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/backgroundtile.png",
		"images/player-sheet0.png",
		"images/solidtile.png",
		"images/jumpthrutile.png",
		"images/thing-sheet0.png",
		"images/troph-sheet0.png",
		"images/particles.png",
		"images/trigger-sheet0.png",
		"media/code.m4a",
		"media/code.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"c2mp-net.js",
		"c2mp-peer.js",
		"c2mp.js",
		"waker.js"
	]
}